"""add city_stats table

Revision ID: a26821c6492e
Revises: 1e3e65c46c97
Create Date: 2026-01-31 19:24:03.146003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a26821c6492e'
down_revision: Union[str, None] = '1e3e65c46c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('gdp', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('gdp_per_capita', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('avg_salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('living_cost_index', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('housing_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('avg_temp_year', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('avg_temp_summer', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('avg_temp_winter', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('rainfall', sa.Integer(), nullable=True),
    sa.Column('sunny_days', sa.Integer(), nullable=True),
    sa.Column('air_quality_index', sa.Integer(), nullable=True),
    sa.Column('area', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_year', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('city_stats')
    # ### end Alembic commands ###
